2020-08-15 07:47:24,565 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'available_apps', '{"lang": "en", "series": "trusty", "arch": "i386"}']'
2020-08-15 07:47:24,566 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-08-15 07:47:24,567 - softwarecenter.db.update - WARNING - update_from_software_center_agent: error: 'WARNING:__main__:no data\n'
2020-08-19 14:26:50,218 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2020-08-19 14:26:50,483 - softwarecenter.db.database - ERROR - failed to add apt-xapian-index
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/database.py", line 194, in _get_new_xapiandb
    softwarecenter.paths.APT_XAPIAN_INDEX_DB_PATH)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 3667, in __init__
    _xapian.Database_swiginit(self,_xapian.new_Database(*args))
DatabaseOpeningError: Couldn't stat '/var/lib/apt-xapian-index/index' (No such file or directory)
2020-08-19 14:26:53,358 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2020-08-19 14:26:53,700 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2020-08-19 14:26:53,719 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2020-08-19 14:26:53,881 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2020-08-19 14:26:58,924 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'exhibits', '{"lang": "en", "series": "trusty"}']'
2020-08-19 14:26:58,925 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-08-19 14:26:59,324 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'RatingsAndReviewsAPI', 'review_stats']'
2020-08-19 14:26:59,324 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-08-19 14:27:01,232 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'available_apps', '{"lang": "en", "series": "trusty", "arch": "i386"}']'
2020-08-19 14:27:01,233 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-08-19 14:27:01,233 - softwarecenter.db.update - WARNING - update_from_software_center_agent: error: 'WARNING:__main__:no data\n'
2020-08-19 15:22:39,543 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2020-08-19 15:22:40,082 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2020-08-19 15:22:40,084 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2020-08-19 15:22:40,150 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2020-08-19 15:22:40,521 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'RatingsAndReviewsAPI', 'review_stats']'
2020-08-19 15:22:40,522 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-08-19 15:22:41,476 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'exhibits', '{"lang": "en", "series": "trusty"}']'
2020-08-19 15:22:41,477 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-08-19 15:22:44,269 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'available_apps', '{"lang": "en", "series": "trusty", "arch": "i386"}']'
2020-08-19 15:22:44,270 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-08-19 15:22:44,271 - softwarecenter.db.update - WARNING - update_from_software_center_agent: error: 'WARNING:__main__:no data\n'
2020-08-19 15:22:44,298 - softwarecenter.db.utils - INFO - software-center-agent finished with status 1
